"""What the bus needs to know about one MCP client.

Two things differ between clients. At run time, their hook protocol: where
the payload says which repo the session is in, and what a hook must print
to inject context or to keep the agent from stopping (`HookDialect`;
everything else about draining an inbox is shared and lives in `hooks.py`).
At `agent-bus init` time, their config files: where an MCP server and its
hooks are declared, and how to tell our entries from the user's
(`ClientWiring`).
"""

from __future__ import annotations

import json
import os
import shlex
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Protocol


class HookDialect(Protocol):
    def repo_from_payload(self, payload: dict) -> str | None:
        """The session's working directory, if the payload carries one."""

    def prompt_output(self, context: str | None) -> str:
        """Stdout for the hook that runs before the model sees a prompt.
        `context` is the text to inject, or None when the inbox was empty."""

    def stop_output(self, reason: str | None) -> str:
        """Stdout for the hook that runs when the agent is about to stop.
        `reason` is why it must keep going, or None to let it stop."""


class StandardHookDialect:
    """The contract Claude Code introduced and several clients adopted:
    plain stdout becomes context, and a `{"decision": "block"}` object keeps
    the turn open. Also the fallback for a client we have no adapter for."""

    def repo_from_payload(self, payload: dict) -> str | None:
        cwd = payload.get("cwd")
        return cwd if isinstance(cwd, str) and cwd else None

    def prompt_output(self, context: str | None) -> str:
        return f"{context}\n" if context else ""

    def stop_output(self, reason: str | None) -> str:
        if not reason:
            return ""
        return json.dumps({"decision": "block", "reason": reason}) + "\n"


# --------------------------- wiring (agent-bus init) ---------------------

MANAGED_DESCRIPTION = (
    "Auto-generated by `agent-bus init`. "
    "Safe to regenerate; safe to delete to opt this repo out."
)
SERVER_KEY = "agent-bus"
HOOK_SUBCOMMANDS = ("hook-user-prompt", "hook-stop")


class WiringStatus(Enum):
    ABSENT = "absent"            # nothing of ours in this client's config
    MANAGED = "managed"          # our own earlier output — safe to rewrite
    HANDWRITTEN = "handwritten"  # an `agent-bus` entry we did not write
    UNREADABLE = "unreadable"    # a config file we cannot parse, so cannot merge


class UnreadableConfigError(ValueError):
    """A config file exists but is not something we can merge into. Writing
    it anyway would throw away whatever the user has in there."""

    def __init__(self, path: Path, problem: str) -> None:
        self.path = path
        super().__init__(f"{path}: {problem}")


@dataclass(frozen=True)
class WiringState:
    status: WiringStatus
    name: str | None = None  # the agent name currently wired, when known
    # False when even --force cannot help: the entry is in a format we can
    # only rewrite between our own markers, and this one has none.
    can_force: bool = True


class ClientWiring(Protocol):
    """How `agent-bus init` wires one MCP client into a repo."""

    client_id: str
    # What this client cannot do, in words for the person running init.
    limitations: tuple[str, ...]

    def files(self, repo: Path) -> list[Path]:
        """Every file `apply` may write, for dry-runs and .gitignore hints."""

    def inspect(self, repo: Path) -> WiringState:
        """What is wired for this client in `repo` right now."""

    def apply(self, repo: Path, *, name: str, bin_path: str) -> None:
        """Write the MCP server entry and the hooks, preserving everything
        in those files that is not ours."""


def is_managed_server(command: object, args: object) -> bool:
    """Our structural fingerprint: the command is an agent-bus binary and
    the first argument is `serve`."""
    if not isinstance(command, str) or not isinstance(args, list):
        return False
    return "agent-bus" in command and bool(args) and args[0] == "serve"


def hook_command(
    *, name: str | None, bin_path: str, subcommand: str, client: str
) -> str:
    """The shell command for one hook. With `name=None` the hook works out
    its agent from the payload instead, which keeps the command identical
    across repos.

    `--client` doubles as the owner tag: a config file shared by several
    clients can hold one managed hook per client without them clobbering
    each other.

    The trailing `|| true` is what makes an uninstalled, half-upgraded or
    otherwise unusable `agent-bus` harmless. Several clients read a non-zero
    exit from an end-of-turn hook as "keep going, here is why" and show the
    hook's stderr as the reason, so without it a broken binary would hold
    every turn open quoting an error. Delivering mail is best-effort;
    blocking is deliberate and travels on stdout, which this does not
    touch."""
    prefix = f"AGENT_BUS_NAME={shlex.quote(name)} " if name else ""
    return (
        f"{prefix}{shlex.quote(bin_path)} {subcommand} --client {client} || true"
    )


def hook_owner(command: str) -> str | None:
    """The client a managed hook command belongs to; None if the command is
    not one of ours. Hooks written before per-client identities carry no
    tag and read as `""` — the file's own client claims those."""
    if "agent-bus" not in command:
        return None
    if not any(sub in command for sub in HOOK_SUBCOMMANDS):
        return None
    words = command.split()
    if "--client" not in words[:-1]:
        return ""
    return words[words.index("--client") + 1]


def group_owners(group: object) -> set[str]:
    """Owners of the hooks in one `{"hooks": [{"command": ...}]}` group —
    the shape Claude Code introduced and other clients reuse."""
    if not isinstance(group, dict) or not isinstance(group.get("hooks"), list):
        return set()
    owners = (
        hook_owner(h.get("command", "")) for h in group["hooks"] if isinstance(h, dict)
    )
    return {o for o in owners if o is not None}


def load_json_object(path: Path) -> dict:
    """The file as a dict; a missing or empty file reads as `{}`.

    Raises UnreadableConfigError for anything else we cannot merge into —
    comments, a syntax error, a top-level array — rather than treating it as
    empty and overwriting it.
    """
    if not path.exists():
        return {}
    try:
        raw = read_config_text(path)
        data = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError as e:
        raise UnreadableConfigError(path, f"not valid JSON ({e.msg}, line {e.lineno})") from None
    if not isinstance(data, dict):
        raise UnreadableConfigError(path, "top level is not a JSON object")
    return data


def read_config_text(path: Path) -> str:
    """A config file's text. Anything we cannot read as UTF-8 is somebody
    else's file, not ours to rewrite."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError as e:
        raise UnreadableConfigError(path, str(e)) from None
    except UnicodeDecodeError as e:
        raise UnreadableConfigError(path, f"not valid UTF-8 (byte {e.start})") from None


def write_config_text(path: Path, text: str) -> None:
    """Write `text` to `path` without a window where the file is empty.

    These are files the user maintains: a crash or a full disk partway
    through a plain write would truncate whatever they had. Writing beside
    the target and renaming means the file is either the old one or the new
    one, never half of either.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.agent-bus-tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def write_json_object(path: Path, data: dict) -> None:
    write_config_text(path, json.dumps(data, indent=2) + "\n")
