"""Bulk wire `agent-bus` into many git repos at once.

Each repo gets:

  1. ``.mcp.json`` — adds (or refreshes) only the ``mcpServers.agent-bus``
     entry. Other MCP servers in the same file are preserved untouched.
  2. ``.claude/settings.json`` — merges the Stop / UserPromptSubmit
     hook commands and the six ``mcp__agent-bus__*`` permission entries.
     Existing hooks for other tools and other allow-list entries are
     preserved.

The agent name is derived from the repo's basename by default (e.g.
``~/websites/acme.dev`` → ``acme-dev``). Two overrides:

  * A per-repo ``.agent-bus-name`` file (one line, the desired name).
  * The ``--name`` CLI flag (single-repo init only).

A ``.agent-bus-ignore`` file in any repo causes that repo to be
skipped during bulk scans.

Idempotency: re-running ``agent-bus init`` against the same repo
produces no change because we detect our own structural fingerprint
(``command`` references ``agent-bus`` and ``args[0] == "serve"``).
Hand-written entries with a different shape are left alone unless
the user passes ``--force``.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Iterable

NAME_FILE = ".agent-bus-name"
IGNORE_FILE = ".agent-bus-ignore"
MAX_NAME_LEN = 40
DEFAULT_SCAN_DEPTH = 6

ALLOW_TOOLS = (
    "mcp__agent-bus__whoami",
    "mcp__agent-bus__list_agents",
    "mcp__agent-bus__send_message",
    "mcp__agent-bus__read_inbox",
    "mcp__agent-bus__read_thread",
    "mcp__agent-bus__tail_audit",
)

MANAGED_DESCRIPTION = (
    "Auto-generated by `agent-bus init`. "
    "Safe to regenerate; safe to delete to opt this repo out."
)


# --------------------------- slugify -----------------------------------


_NON_SLUG = re.compile(r"[^a-z0-9-]+")
_DASHES = re.compile(r"-+")


def slugify(name: str) -> str:
    s = name.lower()
    s = s.replace("_", "-").replace(".", "-")
    s = re.sub(r"\s+", "-", s)
    s = _NON_SLUG.sub("-", s)
    s = _DASHES.sub("-", s).strip("-")
    if not s:
        s = "repo"
    return s[:MAX_NAME_LEN]


def resolve_name(
    repo: Path,
    *,
    prefix: str | None = None,
    override: str | None = None,
) -> str:
    """Determine the agent name for `repo`.

    Priority: explicit override > per-repo .agent-bus-name file > slug.
    The slug is applied to ``override`` too when it comes from a file,
    so users can't accidentally pin an invalid name.
    """
    if override:
        return slugify(override)
    name_file = repo / NAME_FILE
    if name_file.exists():
        try:
            raw = name_file.read_text(encoding="utf-8").strip()
            if raw:
                return slugify(raw)
        except OSError:
            pass
    derived = slugify(repo.name)
    if prefix:
        derived = slugify(f"{prefix}-{derived}")
    return derived


def deconflict_names(plans: list["InitPlan"]) -> None:
    """In-place: rename plans whose slugs collide so each one is unique.

    The first occurrence keeps the bare slug; subsequent collisions
    get the parent-dir prefixed.
    """
    by_name: dict[str, list[InitPlan]] = {}
    for p in plans:
        by_name.setdefault(p.name, []).append(p)
    for name, group in by_name.items():
        if len(group) <= 1:
            continue
        # keep first as-is, rename the rest
        for p in group[1:]:
            parent = slugify(p.repo.parent.name)
            p.name = slugify(f"{parent}-{name}")
            p.notes.append(f"renamed to deconflict with {group[0].repo}")


# --------------------------- repo detection ----------------------------


def is_git_repo(path: Path) -> bool:
    """A directory with .git (file or directory) is a git working copy."""
    return (path / ".git").exists()


def has_ignore_marker(path: Path) -> bool:
    return (path / IGNORE_FILE).exists()


def find_git_repos(
    root: Path, *, max_depth: int = DEFAULT_SCAN_DEPTH
) -> list[Path]:
    """Return git repos under `root`, skipping nested repos and a few
    obvious dirs (node_modules / .venv / vendor) for speed."""
    root = root.expanduser().resolve()
    if not root.exists():
        return []
    if is_git_repo(root):
        return [root]

    skip_dirs = {
        ".git", "node_modules", ".venv", "venv", "__pycache__",
        ".tox", ".mypy_cache", ".pytest_cache", ".ruff_cache",
        "vendor", "build", "dist", ".next", ".nuxt",
    }
    out: list[Path] = []
    stack: list[tuple[Path, int]] = [(root, 0)]
    while stack:
        dirpath, depth = stack.pop()
        try:
            entries = list(dirpath.iterdir())
        except (OSError, PermissionError):
            continue
        if any(e.name == ".git" for e in entries):
            out.append(dirpath)
            continue  # do not descend into a git repo (skip submodules)
        if depth >= max_depth:
            continue
        for e in entries:
            if not e.is_dir():
                continue
            if e.is_symlink():
                continue
            if e.name in skip_dirs:
                continue
            if e.name.startswith("."):
                # hidden dirs other than .git are usually editor/config
                # state — don't recurse into them.
                continue
            stack.append((e, depth + 1))
    out.sort()
    return out


# --------------------------- agent-bus binary path ---------------------


def detect_agent_bus_bin(explicit: str | None = None) -> str:
    """Best-effort: explicit > $AGENT_BUS_BIN env > shutil.which > bare command.

    Returns the path as PATH gives it to us (typically the pipx shim at
    ``~/.local/bin/agent-bus``). We deliberately do **not** resolve symlinks:
    pipx shims survive `pipx upgrade` / `pipx reinstall` and even package
    renames, while the underlying venv path moves and breaks every wiring
    that baked in the resolved target.
    """
    if explicit:
        return explicit
    import os

    env_path = os.environ.get("AGENT_BUS_BIN")
    if env_path:
        return env_path
    found = shutil.which("agent-bus")
    if found:
        return found
    return "agent-bus"


# --------------------------- file builders ----------------------------


def build_mcp_entry(*, name: str, repo: Path, bin_path: str) -> dict:
    """Canonical shape — kept in one place so `is_managed_entry()` can
    recognise our previous output on re-runs."""
    return {
        "command": bin_path,
        "args": ["serve"],
        "env": {
            "AGENT_BUS_NAME": name,
            "AGENT_BUS_REPO": str(repo),
        },
        "description": MANAGED_DESCRIPTION,
    }


def is_managed_mcp_entry(entry: dict | None) -> bool:
    if not isinstance(entry, dict):
        return False
    cmd = entry.get("command", "")
    args = entry.get("args", [])
    if not isinstance(cmd, str) or not isinstance(args, list):
        return False
    if "agent-bus" not in cmd:
        return False
    if not args or args[0] != "serve":
        return False
    return True


def build_hook_commands(*, name: str, bin_path: str) -> tuple[dict, dict]:
    """Return (user_prompt_hook_block, stop_hook_block) ready to splice
    into .claude/settings.json's hooks.* arrays."""
    base = lambda sub: {
        "matcher": "",
        "hooks": [
            {
                "type": "command",
                "command": f"AGENT_BUS_NAME={name} {bin_path} {sub}",
            }
        ],
    }
    return base("hook-user-prompt"), base("hook-stop")


def is_managed_hook_block(block: dict) -> bool:
    if not isinstance(block, dict):
        return False
    hooks = block.get("hooks") or []
    if not isinstance(hooks, list):
        return False
    for h in hooks:
        cmd = (h or {}).get("command", "") if isinstance(h, dict) else ""
        if "agent-bus" in cmd and (
            "hook-user-prompt" in cmd or "hook-stop" in cmd
        ):
            return True
    return False


# --------------------------- planning + dry-run ------------------------


class Action(Enum):
    WRITE = "write"          # no agent-bus entry yet → create
    REFRESH = "refresh"      # existing managed entry → update (e.g. name change)
    SKIP_HANDWRITTEN = "skip-handwritten"   # foreign entry, no --force
    SKIP_IGNORED = "skip-ignored"
    SKIP_NOT_REPO = "skip-not-repo"


@dataclass
class InitPlan:
    repo: Path
    name: str
    action: Action
    previous_name: str | None = None
    notes: list[str] = field(default_factory=list)

    @property
    def is_change(self) -> bool:
        return self.action in (Action.WRITE, Action.REFRESH)


def plan_for_repo(
    repo: Path,
    *,
    prefix: str | None = None,
    override: str | None = None,
    force: bool = False,
    bin_path: str | None = None,
) -> InitPlan:
    repo = repo.expanduser().resolve()
    if not is_git_repo(repo):
        return InitPlan(repo=repo, name="", action=Action.SKIP_NOT_REPO)
    if has_ignore_marker(repo):
        return InitPlan(repo=repo, name="", action=Action.SKIP_IGNORED)

    name = resolve_name(repo, prefix=prefix, override=override)

    mcp_path = repo / ".mcp.json"
    previous_name: str | None = None
    if mcp_path.exists():
        try:
            existing = json.loads(mcp_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            existing = {}
        entry = (existing.get("mcpServers") or {}).get("agent-bus")
        if entry is not None:
            if is_managed_mcp_entry(entry):
                previous_name = (entry.get("env") or {}).get("AGENT_BUS_NAME")
                action = Action.REFRESH
            elif force:
                action = Action.REFRESH
                previous_name = (entry.get("env") or {}).get("AGENT_BUS_NAME")
            else:
                return InitPlan(
                    repo=repo,
                    name=name,
                    action=Action.SKIP_HANDWRITTEN,
                )
        else:
            action = Action.WRITE
    else:
        action = Action.WRITE

    plan = InitPlan(repo=repo, name=name, action=action, previous_name=previous_name)
    if previous_name and previous_name != name:
        plan.notes.append(f"renaming from '{previous_name}' to '{name}'")
    return plan


def plan_for_paths(
    paths: Iterable[Path],
    *,
    scan: bool,
    prefix: str | None = None,
    override: str | None = None,
    force: bool = False,
    bin_path: str | None = None,
) -> list[InitPlan]:
    repos: list[Path] = []
    for p in paths:
        p = p.expanduser().resolve()
        if scan:
            repos.extend(find_git_repos(p))
        else:
            repos.append(p)
    plans = [
        plan_for_repo(
            r,
            prefix=prefix,
            override=override if not scan else None,
            force=force,
            bin_path=bin_path,
        )
        for r in repos
    ]
    deconflict_names([p for p in plans if p.is_change])
    return plans


# --------------------------- apply ------------------------------------


def _merge_mcp_json(
    path: Path, *, name: str, repo: Path, bin_path: str
) -> None:
    data: dict = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                data = {}
        except (OSError, json.JSONDecodeError):
            data = {}
    servers = data.get("mcpServers")
    if not isinstance(servers, dict):
        servers = {}
    servers["agent-bus"] = build_mcp_entry(name=name, repo=repo, bin_path=bin_path)
    data["mcpServers"] = servers
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _merge_claude_settings(
    path: Path, *, name: str, bin_path: str
) -> None:
    data: dict = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(data, dict):
                data = {}
        except (OSError, json.JSONDecodeError):
            data = {}

    # ---- permissions.allow merge (dedupe, keep order) -----------------
    perms = data.get("permissions")
    if not isinstance(perms, dict):
        perms = {}
    allow = perms.get("allow")
    if not isinstance(allow, list):
        allow = []
    seen = set(allow)
    for tool in ALLOW_TOOLS:
        if tool not in seen:
            allow.append(tool)
            seen.add(tool)
    perms["allow"] = allow
    data["permissions"] = perms

    # ---- hooks merge: replace any prior agent-bus hook block ----------
    hooks = data.get("hooks")
    if not isinstance(hooks, dict):
        hooks = {}
    user_prompt_block, stop_block = build_hook_commands(name=name, bin_path=bin_path)

    for event, new_block in (
        ("UserPromptSubmit", user_prompt_block),
        ("Stop", stop_block),
    ):
        existing_list = hooks.get(event)
        if not isinstance(existing_list, list):
            existing_list = []
        kept = [b for b in existing_list if not is_managed_hook_block(b)]
        kept.append(new_block)
        hooks[event] = kept
    data["hooks"] = hooks

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def apply_plan(plan: InitPlan, *, bin_path: str) -> None:
    """Write the .mcp.json and .claude/settings.json for one repo.

    Assumes `plan.is_change` is True; callers should filter SKIP_*.
    """
    if not plan.is_change:
        return
    _merge_mcp_json(
        plan.repo / ".mcp.json",
        name=plan.name,
        repo=plan.repo,
        bin_path=bin_path,
    )
    _merge_claude_settings(
        plan.repo / ".claude" / "settings.json",
        name=plan.name,
        bin_path=bin_path,
    )


def summarise(plans: list[InitPlan]) -> dict[str, int]:
    counts: dict[str, int] = {a.value: 0 for a in Action}
    counts["rename"] = 0
    for p in plans:
        counts[p.action.value] += 1
        if p.is_change and p.previous_name and p.previous_name != p.name:
            counts["rename"] += 1
    return counts
